### ISSUE TITLE
The courses dataset it not right. 

### ISSUE THREAD

**Issue by arieling** [cobalt-uoft/datasets#3]
It only contains Courses starting with A now.

**Comment by qasim** [comment]
Thanks for reporting @arieling!

From my first look, uoft-scrapers was fine, but during the sorting / filtering, it stopped prematurely. I'll investigate. In the meanwhile, I've reverted `courses.json` to last full version.

**Comment by qasim** [comment]
(for the record, this does not affect our hosted API)
