### ISSUE TITLE
Courses dataset does not reflect the latest changes in uoft-scrapers

### ISSUE THREAD

**Issue by chintans1** [cobalt-uoft/datasets#4]
The UTSC breadths are still left unpopulated but the latest changes in uoft-scrapers should populate it. I guess the module needs to get updated on the server to use the latest changes?

**Comment by qasim** [comment]
That's right. Next I'm at my computer, I'll release a new version of uoft-scrapers and update the machine.

**Comment by chintans1** [comment]
@qasim hey just wanted to remind again!

**Comment by isthisnagee** [comment]
I think @qasim is on vacation rn.
